import { StyleSheet } from 'react-native';
import {colors} from './colors';

export const Styles = StyleSheet.create({
    bellinowDiv:{
        backgroundColor:'#fff',
        padding:10,
        flexDirection:'row',
        justifyContent:'space-between',
        paddingBottom:20,
        paddingRight:20,
        paddingTop:15
    },
    belinoImg:{
        flexDirection:'row'
    }
    ,
    main:{
        flex:1,
        backgroundColor:colors.background
    },
    radioDiv:{
        height:15,
        width:15,
        borderWidth:1,
        borderRadius:7.5,
        padding:2,
        justifyContent:'center',
        alignItems:'center'
    },
    csvInput:{
        height:30,
        width:80,
        borderWidth:0.5,
        borderColor:colors.bottomColor,
        backgroundColor:'#fff',
        marginRight:2,
        paddingLeft:5,
        fontSize:12
    },
    creditSelect:{
        flexDirection:'row',
        padding:10,
        backgroundColor:'#FBEEE4',
        justifyContent:'space-between',
        alignItems:'center',
        paddingRight:20,
        paddingBottom:30
    },
    recText:{
        color:'grey',
        fontWeight:'bold',
        fontSize:12,
        marginLeft:10,
        marginBottom:5
    },
    radio:{
        height:10,
        width:10,
        borderRadius:5
    },
    fundsInsufficient:{
        color:'#B39904',
        fontSize:12,
        marginRight:5
    },
    btn:{
        height:45,
        justifyContent:'center',
        alignItems:'center'
    },
    belinowSelect:{
        marginTop:5,
        flexDirection:'row'
    },
    iconImage0:{
        height:10,
        width:30,
        resizeMode:'contain',
        marginRight:5,
        marginTop:-20
    },iconImage:{
        height:20,
        width:49,
        resizeMode:'contain'
    },
    iconImage1:{
        height:28,
        width:55,
        resizeMode:'contain'
    },
    iconImage2:{
        height:20,
        width:30,
        resizeMode:'contain',
        marginRight:5
    },
    header:{
        height:50,
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center',
        marginBottom:10
    },
    headerBtn:{
        flex:10,
        height:50,
        justifyContent:'center',
        alignItems:'center'
    },
    titleDiv:{
        flex:90,
        justifyContent:'center',
        alignItems:'center'
    },
    payMethod:{
        flexDirection:'row',
        padding:5,
        justifyContent:'space-between',
        backgroundColor:'#fff',
        borderBottomColor: colors.background,
        borderBottomWidth:1,
        paddingTop:15,
        paddingBottom:15,
        paddingRight:15
    },
    voucher:
     {
        flexDirection:'row',
        flex:1,
        backgroundColor:'#fff',
        padding:10,
        alignItems:'center'
    },
    voucherInput:{
        flex:80,
        borderColor:colors.bottomColor,
        borderWidth:0.5,
        marginBottom:5,
        borderRadius:2,
        marginRight:10,
        height:35,
        paddingLeft:5
       },
       applyBtn:{
         flex:20,
         paddingLeft:8,
         paddingRight:8,
         height:35,
         backgroundColor:colors.main,
         alignItems:'center',
         justifyContent:'center',
         borderRadius:2
       },
       error:{
        color:'red',
         fontSize:12
    }
})